### ISSUE TITLE
Not working and possibility to cancel form  when interacting with quest items

### ISSUE THREAD

**Issue by astothialo** [raethkcj/CancelShapeshift#1]
Hello, love the idea of the mod. It is much appreciated and much needed :)
It seems it doesnt work at all. Benn right clicking on npc's in the crossroads and it does nothing.

Also, any chance you could have it cancel form when interacting with quest items?

thank you for your work!

**Comment by raethkcj** [comment]
Possibly fixed in #2 , could you try it again?

If it's still not working could you type this into your chatbox:

`/console scriptErrors 1`

and try again, and let me know if any errors pop up?

I added the ability to cancel shapeshift when using items by default, and added an option to cancel it when using abilities (I recommend you don't use that option, but it's there if you need it)

**Comment by astothialo** [comment]
hi, appreciate you working on a fix.
typing /cs brings up the options but still not working when talking to npcs or interacting with objects.

and theres are no errors popping up at all.

**Comment by raethkcj** [comment]
Hmm, would you mind helping me debug this? It's working for me with all NPCs so far so I'm not sure what's happening for you.

1. Find an NPC you can talk to in the absolute middle of nowhere, preferably with zero other players nearby (other player actions will clutter the logs)

2. Make sure your character is in Ghost Wolf form.

3. Run `/console scriptErrors 1`

3. Make three macros with the following scripts, and put all three on easily reachable keybinds:

    1. `/run local f=CreateFrame("Frame"); f:RegisterEvent("UI_ERROR_MESSAGE"); f:SetScript("OnEvent", function(self,event,...) DEFAULT_CHAT_FRAME:AddMessage(select(1,...)); DEFAULT_CHAT_FRAME:AddMessage(select(2,...)) end)
`
    1. `/etrace`
    1. `/etrace stop`

4. Run `macro i` first, make sure to only press it once. 

5. The timing matters in this step. Press `macro ii`, then right click on your NPC, then press `macro iii`. This has to be done pretty quickly to make sure that `etrace` doesn't capture unrelated game events.

6. Take a full screenshot of your game and attach it here.

**Comment by astothialo** [comment]
hi, sorry didn't see this until now.
I'm playing as a Druid, maybe it's not working because of that?

**Comment by raethkcj** [comment]
It's possible, I don't have a 10+ druid to try it on. The function I'm using actually says it *only* works for druid, but I tried it and it worked for ghost wolf. Druids might trigger different game events when trying to talk/use items, so I think it'd still be worth getting some logs. Every form *should* be the same but who knows.

**Comment by astothialo** [comment]
![WoWScrnShot_090619_182333](https://user-images.githubusercontent.com/52817006/64412817-9780fa80-d0d3-11e9-8d8a-bd83303d0346.jpg)

**Comment by raethkcj** [comment]
Thanks for that! Unfortunately, the events and error are identical to what I get on a shaman, so there's still no clear reason it's not working.

The last thing I can think of for now is to just try running `/run CancelShapeshiftForm()` while in every form you have available. Doesn't matter where you are, there should be no errors.

If running that *does* pop you out of form, then something strange is going on and I'll level up a druid and try to figure it out.

If it *doesn't* work then it might be a bug on Blizzard's end and I'll make a report on the forums and hope they get around to fixing it.

**Comment by astothialo** [comment]
sad times :(
have you had a look at ezdismount for 1.12 wow client?
might have something in there to make it easier :D

**Comment by astothialo** [comment]
Running /run CancelShapeshiftForm() in any form and interacting with an NPC does not shift me out of form :(

ALso here is a link to Ezdismount that druids used in Vanilla/pservers.
https://legacy-wow.com/vanilla-addons/ezdismount/
Hope it helps :D

**Comment by raethkcj** [comment]
Finally got around to leveling a druid after all the DDoS this weekend. 

It looks like Blizzard has intentionally disabled this function on druids, and has gone to great lengths to make sure this can't be done. The API that vanilla addons used has been protected since TBC. The function I'm trying to use worked for some time after that, but was also eventually made protected (but still somehow works for shamans, which I don't quite understand.)

Without a change of heart on Blizzard's end, this addon won't work for druids, sadly.
